# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colMax <- function(mat, na_rm = FALSE) {
    .Call('RPtests_colMax', PACKAGE = 'RPtests', mat, na_rm)
}

